version: '3'
services:
  database:
    image: mariadb:10.6
    container_name: database
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_INITDB_SKIP_TZINFO=yes
      - TZ="Europe/Budapest"
    ports:
      - 3306:3306
    logging:
      driver: json-file
      options:
        max-size: '1m'
        max-file: '3'

  prestashop:
    build:
      context: .docker/prestashop
      dockerfile: Dockerfile
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=database
      - PRESTASHOP_DATABASE_PORT_NUMBER=${DB_PORT}
      - PRESTASHOP_DATABASE_USER=${DB_USER}
      - PRESTASHOP_DATABASE_PASSWORD=${DB_PASSWORD}
      - PRESTASHOP_DATABASE_NAME=${DB_DATABASE}
    volumes:
      - ./prestashop:/bitnami/prestashop
    depends_on:
      - database

volumes:
  mariadb_data:
    driver: local
